# 1. Server Config
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: ENC(QNchFVJLPg19xTYyjbM2WCRVIiAAZFJqQL3epsD9GufJl3yx6KwkqsfagKyplY1LLS63UY6pdpZX/xCy16073C+CYEgVVirlIoh/61th75Y=)
    username: ENC(x0MI4+flphCUA9uwSe5E1YjQR1RqZwbW)
    password: ENC(nnfXWWddf2J6fomi4HX+gw==)

# 3. MyBatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # dto 변수 이름과 db 칼럼 이름 매칭용


# 4. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 5. App
app:
  key:
    kakaoApiKey: ENC(TbeZheIzhR4CUxKFbDqQmpdsqGKx7B6iq2KPQWOJDNdnTnnF4c/2+P21YIQutNyp)
    kakaoJSApiKey: ENC(lGwCEAx0P3L2qe9jVYdq/MWXt3zWLnrfceWkdpUG3wfRzwEIogbx4qJXv7Bflw+R)
    googleApiKey: ENC(2ZntVl7VItdoFSR9MFm7sAt+lVmV5ejY3yt6QkQ+IN73AtS8HAgkbiIN58cA+vNMaDSq94dpyUeWuWYylyhb5Yynf+BMKyqbIBo0m07c2n/fvicFmwE7Hw==)
    googleApiSecretKey: ENC(wqRdJ0edAHlyzC1s2qTfgPRTOdXdX/L2v342Vs7NTifnbaqOHuIAIH6Iu2B1CDed)
    naverApiKey: ENC(W21CWi5vucRAWCqK4GMx1P+L27Q66k3kJRU/e0BOyxs=)
    naverApiSecretKey: ENC(P7kspdfWVZVOh9kr3DG+ogt3pyebrCLy)
  dir:
    imgdir: file:///C:/Users/yejin/Documents/github/altspace/imgs/  # 화면 출력 용
    uploadimgdir: C:/Users/yejin/Documents/github/altspace/imgs/    # 파일 Write 용
  url:
    serverUrl : http://127.0.0.1:9090

# 6. jasypt
jasypt:
  encryptor:
    password: space
    algorithm: PBEWithMD5AndDES