# 1. Server Config
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: ENC(QNchFVJLPg19xTYyjbM2WCRVIiAAZFJqQL3epsD9GufJl3yx6KwkqsfagKyplY1LLS63UY6pdpZX/xCy16073C+CYEgVVirlIoh/61th75Y=)
    username: ENC(x0MI4+flphCUA9uwSe5E1YjQR1RqZwbW)
    password: ENC(nnfXWWddf2J6fomi4HX+gw==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(fcbXljrvHYVXH8a7JdHTwIGaekY73TAe) # SMTP 서버 로그인 아이디
    password: ENC(pdKdKoikGgInBKZ+QYgCZ5U0jPurgi1rnx3rzbAanDU=) # SMTP 서버 로그인 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부

# 3. MyBatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # dto 변수 이름과 db 칼럼 이름 매칭용


# 4. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 5. App
app:
  key:
    kakaoApiKey: ENC(TbeZheIzhR4CUxKFbDqQmpdsqGKx7B6iq2KPQWOJDNdnTnnF4c/2+P21YIQutNyp)
    kakaoJSApiKey: ENC(lGwCEAx0P3L2qe9jVYdq/MWXt3zWLnrfceWkdpUG3wfRzwEIogbx4qJXv7Bflw+R)
    googleApiKey: ENC(2ZntVl7VItdoFSR9MFm7sAt+lVmV5ejY3yt6QkQ+IN73AtS8HAgkbiIN58cA+vNMaDSq94dpyUeWuWYylyhb5Yynf+BMKyqbIBo0m07c2n/fvicFmwE7Hw==)
    googleApiSecretKey: ENC(wqRdJ0edAHlyzC1s2qTfgPRTOdXdX/L2v342Vs7NTifnbaqOHuIAIH6Iu2B1CDed)
    naverApiKey: ENC(W21CWi5vucRAWCqK4GMx1P+L27Q66k3kJRU/e0BOyxs=)
    naverApiSecretKey: ENC(P7kspdfWVZVOh9kr3DG+ogt3pyebrCLy)
  dir:
    imgdir: file:///C:/Users/yejin/Documents/github/altspace/imgs/  # 화면 출력 용
    uploadimgdir: C:/Users/yejin/Documents/github/altspace/imgs/    # 파일 Write 용
  url:
    serverUrl : http://127.0.0.1:9090

# 6. jasypt
jasypt:
  encryptor:
    password: space
    algorithm: PBEWithMD5AndDES

# 7. NCP
ncp:
  ocr:
    url: ENC(jGflQswiw5J+0d0jYeC0+usqJ410h5kywm+T104JWArSnnz7gh/yVZiJ87eQkgDeF6Qv22oUhHJaVpxu+f0QvClsxGNJSGMduoGa5nXuM9hQLxLCnJ0k0tnWFgwYx5DubMOZvuJsvG6LQfwMs5xRBnhqqsPOH8w4J1TnUjyYS4fzwq8HwVXgDg==)
    key: ENC(ck19pyCQyOkU8qRuKCPrv+2r6m3b7/l1r4171OAuux0mnqQA0BsLCDdGzTv/5iC060k1FvKk2xA=)
  chatbot:
    url: ENC(CSA2EHUtQNrUhIYKwfvkaJz+mBDNBw6Zrw2xjAXz6lAQye8BRP3FEXksrUk+w/d4BvlaURrtKPUHnQ9mblLgyNAVQ+rXtM4od+A8FG9dElLyZviDk0UKQKarZmRSprJVcGPm2DHS+OV0cJKkseQoC3th3gNPQBS5Xwu6Xmvyodg=)
    key: ENC(3gHb4j0kgeZrhn/bvrpGefQqZgNhgpQL94Pd4rH61kJ18qP6bpWYeWu7HyAZduYukes8tANgojY=)
  papago:
    id: ENC(un4U0QCtRNbvsc/y+3E7CVxtdVSFJHxx)
    key: ENC(Aq19Q5y42NHRa6hDp7SuvA9dXSRAjqyotN1TQEuNY7NFiajTFXf8SNfCe6rpLqp9mOzkm4lknkE=)