# 1. Server Config
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://49.50.172.52:3306/altspacedb?characterEncoding=utf8
    username: userdev_NCP #ENC(tflb+WDeXH++6lNNLDKmOA==)
    password: 111111  #ENC(Z3hh8Mdzuse1dxq271vdyg==)

# 3. MyBatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # dto 변수 이름과 db 칼럼 이름 매칭용


# 4. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 5. App
app:
  key:
    kakaoApiKey: d9815fe45ece611b664e99901e3a45b0
    kakaoJSApiKey: abe605724fcc63bdb6710be41d7bb2fd
    googleApiKey: 179241731828-8p6vci91eru8c1c9l9n7d67kmpmba7ls.apps.googleusercontent.com
    googleApiSecretKey: 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
    naverApiKey: GTwwnLrG6H_Hrx4QozHX
    naverApiSecretKey: 8ASwbGFGVj
    algo: PBEWithMD5AndDES
    skey: mykey
  dir:
    imgdir: file:///C:/Users/mnew0/OneDrive/Desktop/altspace/imgs/  # 화면 출력 용
    uploadimgdir: C:/Users/mnew0/OneDrive/Desktop/altspace/imgs/    # 파일 Write 용
  url:
    serverUrl : http://127.0.0.1:9090