# 1. Server Config
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher # Spring Boot 2.6 이상에서는 ant_path_matcher 또는 경로 패턴 매칭 전략을 명시적으로 설정해야 합니다.

  datasource:
    url: jdbc:mysql://49.50.172.52:3306/altspacedb?characterEncoding=utf8
    username: userdev_NCP #ENC(tflb+WDeXH++6lNNLDKmOA==)
    password: 111111  #ENC(Z3hh8Mdzuse1dxq271vdyg==)

# 3. MyBatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # dto 변수 이름과 db 칼럼 이름 매칭용

# 4. Log Level
logging:
  level:
    root: info   #  error < info < debug

# 5. App
app:
  key:
    kakaoApiKey: d9815fe45ece611b664e99901e3a45b0
    kakaoJSApiKey: abe605724fcc63bdb6710be41d7bb2fd
    googleApiKey: 179241731828-8p6vci91eru8c1c9l9n7d67kmpmba7ls.apps.googleusercontent.com
    googleApiSecretKey: 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
    naverApiKey: GTwwnLrG6H_Hrx4QozHX
    naverApiSecretKey: 8ASwbGFGVj
    algo: PBEWithMD5AndDES
    skey: mykey
  dir:
    imgdir: file:///C:/IntelliJ/IntelliJ IDEA 2024.3.4.1/project/altspace/imgs/  # 화면 출력 용
    uploadimgdir: C:/IntelliJ/IntelliJ IDEA 2024.3.4.1/project/altspace/imgs/    # 파일 Write 용
  url:
    serverUrl : http://127.0.0.1:8080

# 6. iamport
imp:
  api:
    key: 0627011552872547
    secretkey: GDyeTp4vo1P5FKiy67lENk5IK52saDFpLW5vPyu2VioRkqVVvxYXpj8atqMsKc8nwywKJLM8g69cPe24

# 7. NCP(OCR 은 혹시나 몰라서 일단 넣어놨어요.)
ncp:
  ocr:
    url: https://tjoxzsvb05.apigw.ntruss.com/custom/v1/41403/f27adacaf33ea3d4f1e97a5ef5c73683d6f2e788d40d9c582d24f9c1676df942/infer
    key: a1R1U21XY05xT1p4d2FOZEtOZXpGTFJoR2NrQllrYk4=
  chatbot:
    url: https://2sw2npiyi7.apigw.ntruss.com/custom/v1/17417/f27adacaf33ea3d4f1e97a5ef5c73683d6f2e788d40d9c582d24f9c1676df942
    key: cm9qYVV4U1RGSVBIY21aVVJrUUFjb2NCWktoaHFWV3g=
  papago:
    id: 7poc0cqw3p
    key: HrLIOMOGp2173lnuNHV73vpFzlb1Y8RGqXt3DpLv
